name: dog_breeds_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.0
  intl: ^0.18.1
  meta: ^1.9.1
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.4	


flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.jpg'

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/

